src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');

Route::group([['as' => 'front-route']], function() {
	Route::get('/about', 'FrontController@about')->name('front.about');
	Route::get('/cekresi', 'FrontController@checkResi');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
	Route::resource('roles','RoleController');
	Route::resource('users','UserController');
});

//User Class Route
Route::group(['middleware' => ['auth'], ['as' => 'user-route']], function() {
	Route::get('/user/selectCourier', 'UserController@selectCourier');
});

// Customer Class Route
Route::group(['middleware' => ['auth'], ['as' => 'customer-route']], function() {
	Route::get('/customer', 'CustomerController@index')->name('customer');
	Route::get('/customer/getCustomer', 'CustomerController@getCustomer')->name('getCustomer');
	Route::post('/customer/getCustomerById', 'CustomerController@getCustomerById')->name('getCustomerById');
	Route::get('/customer/getCustomerType', 'CustomerController@getCustomerType')->name('getCustomerType');
	Route::post('/customer/storeCustomer','CustomerController@storeCustomer')->name('storeCustomer');
	Route::post('/customer/storeCustomerType','CustomerController@storeCustomerType')->name('storeCustomerType');
	Route::post('/customer/destroyCustomer', 'CustomerController@destroyCustomer')->name('destroyCustomer');
	Route::post('/customer/destroyCustomerType','CustomerController@destroyCustomerType')->name('destroyCustomerType');
	Route::post('/customer/updateCustomer','CustomerController@updateCustomer')->name('updateCustomer');
	Route::post('/customer/updateCustomerType','CustomerController@updateCustomerType')->name('updateCustomerType');
	Route::get('/customer/selectCustomerType','CustomerController@selectCustomerType')->name('selectCustomerType');
	Route::get('/customer/selectCustomer', 'CustomerController@selectCustomer');
	Route::get('/customer/report', 'CustomerController@reportCustomer');
});

// Item Class Route
Route::group(['middleware' => ['auth'], ['as' => 'item-route']], function() {
	Route::get('/item', 'ItemController@index')->name('item');
	Route::get('/item/getItem', 'ItemController@getItem')->name('getItem');
	Route::post('/item/getItemPickup', 'ItemController@getItemPickup');
	Route::post('/item/getItemDelivery', 'ItemController@getItemDelivery');
	Route::post('/item/getItemById', 'ItemController@getItemById')->name('getItemById');
	Route::get('/item/getItemCategory1', 'ItemController@getItemCategory1')->name('getItemCategory1');
	Route::get('/item/getItemCategory2', 'ItemController@getItemCategory2')->name('getItemCategory2');
	Route::post('/item/storeItem', 'ItemController@storeItem')->name('storeItem');
	Route::post('/item/storeItemPickup', 'ItemController@storeItemPickup');
	Route::post('/item/storeItemDelivery', 'ItemController@storeItemDelivery');
	Route::post('/item/storeItemCategory1', 'ItemController@storeItemCategory1')->name('storeItemCategory1');
	Route::post('/item/storeItemCategory2', 'ItemController@storeItemCategory2')->name('storeItemCategory2');
	Route::post('/item/destroyItem', 'ItemController@destroyItem')->name('destroyItem');
	Route::post('/item/destroyItemPickup', 'ItemController@destroyItemPickup');
	Route::post('/item/destroyItemDelivery', 'ItemController@destroyItemDelivery');
	Route::post('/item/destroyItemCategory1', 'ItemController@destroyItemCategory1')->name('destroyItemCategory1');
	Route::post('/item/destroyItemCategory2', 'ItemController@destroyItemCategory2')->name('destroyItemCategory2');
	Route::post('/item/updateItem', 'ItemController@updateItem')->name('updateItem');
	Route::post('/item/updateItemCategory1', 'ItemController@updateItemCategory1')->name('updateItemCategory1');
	Route::post('/item/updateItemCategory2', 'ItemController@updateItemCategory2')->name('updateItemCategory2');
	Route::get('/item/selectItem', 'ItemController@selectItem')->name('selectItem');
	Route::get('/item/selectItemCategory1', 'ItemController@selectItemCategory1')->name('selectItemCategory1');
	Route::get('/item/selectItemCategory2', 'ItemController@selectItemCategory2')->name('selectItemCategory2');
	Route::get('/item/report', 'ItemController@reportItem');
});

//Supplier Class Route
Route::group(['middleware' => ['auth'], ['as' => 'supplier-route']], function() {
	Route::get('/supplier', 'SupplierController@index')->name('supplier');
	Route::get('/supplier/getSupplier', 'SupplierController@getSupplier')->name('getSupplier');
	Route::post('/supplier/getSupplierById', 'SupplierController@getSupplierById')->name('getSupplierById');
	Route::post('/supplier/storeSupplier', 'SupplierController@storeSupplier')->name('storeSupplier');
	Route::post('/supplier/destroySupplier', 'SupplierController@destroySupplier')->name('destroySupplier');
	Route::post('/supplier/updateSupplier', 'SupplierController@updateSupplier')->name('updateSupplier');
	Route::get('/supplier/selectSupplier', 'SupplierController@selectSupplier')->name('selectSupplier');
	Route::get('/supplier/report', 'SupplierController@reportSupplier');
});

//Pick Up Class Route
Route::group(['middleware' => ['auth'], ['as' => 'pickup-route']], function() {
	Route::get('/pickup', 'PickupController@index')->name('pickup');
	Route::get('/pickup/active', 'PickupController@pickupActive')->name('pickupActive');
	Route::get('/pickup/activeCourier', 'PickupController@pickupActiveCourier')->name('pickupActiveCourier');
	Route::get('/pickup/cancel', 'PickupController@pickupCancel')->name('pickupCancel');
	Route::get('/pickup/getPickup', 'PickupController@getPickup');
	Route::get('/pickup/getPickupActive', 'PickupController@getPickupActive');
	Route::get('/pickup/getPickupActiveCourier', 'PickupController@getPickupActiveCourier');
	Route::get('/pickup/getPickupCancel', 'PickupController@getPickupCancel')->name('getPickupCancel');
	Route::get('/pickup/getPickupById/{id_pickup}', 'PickupController@getPickupById');
	Route::post('/pickup/getPickupLocation', 'PickupController@getPickupLocation');
	Route::get('/pickup/create', 'PickupController@create')->name('createPickup');
	Route::post('/pickup/storePickup', 'PickupController@storePickup');
	Route::post('/pickup/storeLocation', 'PickupController@storeLocation');
	Route::get('/pickup/changePickupJob', 'PickupController@changePickupJob')->name('changePickupJob');
	Route::get('/pickup/cancelPickup', 'PickupController@cancelPickup')->name('cancelPickup');
	Route::get('/pickup/recyclePickup', 'PickupController@recyclePickup')->name('recyclePickup');
	Route::get('/pickup/updatedActivity', 'PickupController@updatedActivity');
	Route::post('/pickup/report', 'PickupController@reportPickup');
	Route::get('/pickup/note/{id}', 'PickupController@notePickup');
});

//Delivery Class Route
Route::group(['middleware' => ['auth'], ['as' => 'delivery-route']], function() {
	Route::get('/delivery', 'DeliveryController@index')->name('delivery');
	Route::get('/delivery/activeDelivery', 'DeliveryController@activeDelivery')->name('activeDelivery');
	Route::get('/delivery/activeDeliveryCourier', 'DeliveryController@activeDeliveryCourier')->name('activeDeliveryCourier');
	Route::get('/delivery/deliveryCancel', 'DeliveryController@deliveryCancel');
	Route::get('/delivery/getDelivery', 'DeliveryController@getDelivery');
	Route::get('/delivery/getDeliveryActive', 'DeliveryController@getDeliveryActive');
	Route::get('/delivery/getDeliveryActiveCourier', 'DeliveryController@getDeliveryActiveCourier');
	Route::get('/delivery/getDeliveryCancel', 'DeliveryController@getDeliveryCancel');
	Route::get('/delivery/getDeliveryById/{id_delivery}', 'DeliveryController@getDeliveryById');
	Route::post('/delivery/getDeliveryLocation', 'DeliveryController@getDeliveryLocation');
	Route::get('/delivery/createDelivery', 'DeliveryController@createDelivery')->name('createDelivery');
	Route::post('/delivery/storeDelivery', 'DeliveryController@storeDelivery');
	Route::post('/delivery/storeLocation', 'DeliveryController@storeLocation');
	Route::get('/delivery/cancelDelivery', 'DeliveryController@cancelDelivery')->name('cancelDelivery');
	Route::get('/delivery/recycleDelivery', 'DeliveryController@recycleDelivery')->name('recycleDelivery');
	Route::get('/delivery/changeDeliveryJob', 'DeliveryController@changeDeliveryJob')->name('changeDeliveryJob');
	Route::post('/delivery/finishDelivery', 'DeliveryController@finishDelivery');
	Route::post('/delivery/report', 'DeliveryController@reportDelivery');
	Route::get('/delivery/invoice/{id}', 'DeliveryController@invoiceDelivery');
});

//Courier Class Route
Route::group(['middleware' => ['auth'], ['as' => 'courier-route']], function() {
	Route::get('/courier', 'CourierController@index')->name('courier.index');
});

//Other Expenses
Route::group(['middleware' => ['auth'], ['as' => 'other-expenses-route']], function() {
	Route::get('/other_expenses', 'OtherExpensesController@index')->name('otherExpenses');
	Route::get('/other_expenses/getOtherExpenses', 'OtherExpensesController@getOtherExpenses');
	Route::post('other_expenses/storeOtherExpenses', 'OtherExpensesController@storeOtherExpenses');
	Route::post('/other_expenses/destroyOtherExpenses', 'OtherExpensesController@destroyOtherExpenses');
	Route::post('/other_expenses/updateOtherExpenses', 'OtherExpensesController@updateOtherExpenses');
	Route::get('/other_expenses/report', 'OtherExpensesController@reportExpenses');
});

//Setting Route
Route::group(['middleware' => ['auth'], ['as' => 'setting-route']], function() {

src/resources/views/backend/partial/app.blade.php
@include('backend.partial.header')

@include('backend.partial.sidebar')

@yield('content')

@yield('js-route')

@include('backend.partial.footer')

@yield('js')

</body>
</html>

src/resources/views/backend/partial/footer.blade.php
<!-- Begin Page Footer-->
<footer class="main-footer">
	<div class="row">
		<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-start justify-content-lg-start justify-content-md-start justify-content-center">
			<p class="text-gradient-02">Copyright &copy; iamhermawan.com 2018</p>
		</div>
		<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-end justify-content-lg-end justify-content-md-end justify-content-center">
		</div>
	</div>
</footer>
<!-- End Page Footer -->
<a href="#" class="go-top"><i class="la la-arrow-up"></i></a>
</div>
<!-- End Content -->
</div>
<!-- End Page Content -->
</div>
<!-- Begin Vendor Js -->
<script src="{{ asset('template/backend/vendors/js/base/jquery.min.js') }}"></script>
<script src="{{ asset('template/backend/vendors/js/base/core.min.js') }}"></script>
<!-- End Vendor Js -->
<!-- Begin Page Vendor Js -->
<script src="{{ asset('template/backend/vendors/js/nicescroll/nicescroll.min.js') }}"></script>
<script src="{{ asset('template/backend/vendors/js/chart/chart.min.js') }}"></script>
<script src="{{ asset('template/backend/vendors/js/progress/circle-progress.min.js') }}"></script>
<script src="{{ asset('template/backend/vendors/js/app/app.js') }}"></script>
<!-- Datatables -->
<script src="{{ asset('plugins/datatables/js/jquery.dataTables.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.min.js') }}"></script>
<!-- Leaflet -->
<script src="{{ asset('plugins/leaflet/leaflet.js') }}"></script>
<!-- Datepicker -->
<script src="{{ asset('plugins/datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<!-- End Page Vendor Js -->
<!-- Begin Page Snippets -->
<!-- APP Master -->
<script src="{{ asset('js/app_master.js') }}"></script>
<!-- APP Datatables -->
<script type="text/javascript" src="{{ asset('js/app_datatables.js') }}"></script>
<!-- End Page Snippets -->

src/resources/views/backend/partial/header.blade.php
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{ $title }}</title>
	<meta name="description" content="Pickup And Delivery Management System (PUDEMAS)">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Google Fonts -->
	<!--<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
	<script>
		WebFont.load({
			google: {"families":["Montserrat:400,500,600,700","Noto+Sans:400,700"]},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>-->
	<!-- Favicon -->
	<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('template/backend/img/apple-touch-icon.png') }}">
	<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('template/backend/img/favicon-32x32.png') }}">
	<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('template/backend/img/favicon-16x16.png') }}">
	<!-- Stylesheet -->
	<link rel="stylesheet" href="{{ asset('template/backend/vendors/css/base/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ asset('template/backend/vendors/css/base/elisyam-1.5.css') }}">
	<link rel="stylesheet" href="{{ asset('template/backend/vendors/css/base/custom.css') }}">
	<!-- Datatables -->
	<link type="text/css" href="{{ asset('plugins/datatables/css/jquery.dataTables.min.css') }}" rel="stylesheet">
	<!-- Select2 -->
	<link type="text/css" href="{{ asset('plugins/select2/css/select2.min.css') }}" rel="stylesheet">
	<!-- Leaflet -->
	<link rel="stylesheet" href="{{ asset('plugins/leaflet/leaflet.css') }}">
	<!-- Datepicker -->
	<link rel="stylesheet" href="{{ asset('plugins/datepicker/css/bootstrap-datepicker.min.css') }}">
		<!-- Tweaks for older IEs--><!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
	</head>
	<body id="page-top">
		<!-- Begin Preloader -->
		<div id="preloader">
			<div class="canvas">
				<img src="{{ asset('template/backend/img/logo.png') }}" alt="logo" class="loader-logo">
				<div class="spinner"></div>   
			</div>
		</div>
		<!-- End Preloader -->
		<div class="page">
			<!-- Begin Header -->
			<header class="header">
				<nav class="navbar fixed-top">         
					<!-- Begin Search Box-->
					<div class="search-box">
						<button class="dismiss"><i class="ion-close-round"></i></button>
						<form id="searchForm" action="#" role="search">
							<input type="search" placeholder="Search something ..." class="form-control">
						</form>
					</div>
					<!-- End Search Box-->
					<!-- Begin Topbar -->
					<div class="navbar-holder d-flex align-items-center align-middle justify-content-between">
						<!-- Begin Logo -->
						<div class="navbar-header">
							<a href="{{ route('home') }}" class="navbar-brand">
								<div class="brand-image brand-big">
									<img src="{{ asset('template/backend/img/logo-big.png') }}" alt="logo" class="logo-big">
								</div>
								<div class="brand-image brand-small">
									<img src="{{ asset('template/backend/img/logo.png') }}" alt="logo" class="logo-small">
								</div>
							</a>
							<!-- Toggle Button -->
							<a id="toggle-btn" href="#" class="menu-btn active">
								<span></span>
								<span></span>
								<span></span>
							</a>
							<!-- End Toggle -->
						</div>
						<!-- End Logo -->
						<!-- Begin Navbar Menu -->
						<ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center pull-right">
							<!-- Begin Notifications -->
							<!--
							<li class="nav-item dropdown"><a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="la la-bell animated infinite swing"></i><span class="badge-pulse"></span></a>
								<ul aria-labelledby="notifications" class="dropdown-menu notification">
									<li>
										<div class="notifications-header">
											<div class="title">Notifications (4)</div>
											<div class="notifications-overlay"></div>
											<img src="{{ asset('template/backend/img/notifications/01.jpg') }}" alt="..." class="img-fluid">
										</div>
									</li>
									<li>
										<a href="#">
											<div class="message-icon">
												<i class="la la-user"></i>
											</div>
											<div class="message-body">
												<div class="message-body-heading">
													New user registered
												</div>
												<span class="date">2 hours ago</span>
											</div>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="message-icon">
												<i class="la la-calendar-check-o"></i>
											</div>
											<div class="message-body">
												<div class="message-body-heading">
													New event added
												</div>
												<span class="date">7 hours ago</span>
											</div>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="message-icon">
												<i class="la la-history"></i>
											</div>
											<div class="message-body">
												<div class="message-body-heading">
													Server rebooted
												</div>
												<span class="date">7 hours ago</span>
											</div>
										</a>
									</li>
									<li>
										<a href="#">
											<div class="message-icon">
												<i class="la la-twitter"></i>
											</div>
											<div class="message-body">
												<div class="message-body-heading">
													You have 3 new followers
												</div>
												<span class="date">10 hours ago</span>
											</div>
										</a>
									</li>
									<li>
										<a rel="nofollow" href="#" class="dropdown-item all-notifications text-center">View All Notifications</a>
									</li>
								</ul>
							</li>
							-->
							<!-- End Notifications -->
							<!-- User -->
							<li class="nav-item dropdown"><a id="user" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><img src="{{ asset('template/backend/img/avatar/avatar-01.jpg') }}" alt="..." class="avatar rounded-circle"></a>
								<ul aria-labelledby="user" class="user-size dropdown-menu">
									<li class="welcome">
										<a href="#" class="edit-profil"><i class="la la-gear"></i></a>
										<img src="{{ asset('template/backend/img/avatar/avatar-01.jpg') }}" alt="..." class="rounded-circle">
									</li>
									<li>
										<a href="{{ url('/') }}" class="dropdown-item" target="_blank"> 
											Homepage
										</a>
									</li>
									<li class="separator"></li>
									<li>
										<a rel="nofollow" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="dropdown-item logout text-center"><i class="ti-power-off"></i></a>
										<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
											@csrf
										</form>
									</li>
								</ul>
							</li>
							<!-- End User -->
							<!-- Search
							<li class="nav-item d-flex align-items-center"><a id="search" href="#"><i class="la la-search"></i></a>s</li>-->
							<!-- End Search -->
						</ul>
						<!-- End Navbar Menu -->
					</div>
					<!-- End Topbar -->
				</nav>
			</header>
			<!-- End Header -->

src/resources/views/backend/partial/sidebar.blade.php
<!-- Begin Page Content -->
<div class="page-content d-flex align-items-stretch">
	<div class="default-sidebar">
		<!-- Begin Side Navbar -->
		<nav class="side-navbar box-scroll sidebar-scroll">
			<!-- Begin Main Navigation -->
			<ul class="list-unstyled">
				<li id="dashboard-link"><a href="{{ route('home') }}"><i class="la la-home"></i><span>Dashboard</span></a></li>
				@can('master-items')
				<li id="master-link"><a id="master-link2" href="#dropdown-master" aria-expanded="false" data-toggle="collapse"><i class="la la-spinner"></i><span>Data Master</span></a>
					<ul id="dropdown-master" class="collapse list-unstyled pt-0">
						<li><a id="item-link" href="{{ route('item') }}">Data Barang</a></li>
						@can('master-customers')
						<li><a id="customer-link" href="{{ route('customer') }}">Data Customer</a></li>
						@endcan
						@can('master-suppliers')
						<li><a id="supplier-link" href="{{ route('supplier') }}">Data Supplier</a></li>
						@endcan
					</ul>
				</li>
				@endcan
				@can('master-users')
				<li><a href="#dropdown-icons" aria-expanded="false" data-toggle="collapse"><i class="la la-users"></i><span>Manajemen Users</span></a>
					<ul id="dropdown-icons" class="collapse list-unstyled pt-0">
						<li><a href="{{ route('users.index') }}">Data User</a></li>
						@can('master-roles')
						<li><a href="{{ route('roles.index') }}">Manajemen Roles User</a></li>
						@endcan
					</ul>
				</li>
				@endcan
				<li id="pickup-link"><a id="pickup-link2" href="#dropdown-pickup" aria-expanded="false" data-toggle="collapse"><i class="la la-cart-arrow-down"></i><span>Transaksi Pengambilan</span></a>
					<ul id="dropdown-pickup" class="collapse list-unstyled pt-0">
						@role('Admin|Pimpinan')
						<li><a id="pickup-index-link" href="{{ route('pickup') }}">Data Pengambilan Selesai</a></li>
						<li><a id="pickup-active-link" href="{{ route('pickupActive') }}">Data Pengambilan Aktif</a></li>
						<li><a id="pickup-cancel-link" href="{{ url('pickup/cancel') }}">Data Pengambilan Dibatalkan</a></li>
						<li><a id="add-pickup-link" href="{{ route('createPickup') }}">Input Pengambilan</a></li>
						@endrole
						@role('Kurir')
						<li><a id="pickup-active-link" href="{{ route('pickupActiveCourier') }}">Data Pengambilan Aktif</a></li>
						@endrole
					</ul>
				</li>
				<li id="delivery-link"><a id="delivery-link2" href="#dropdown-delivery" aria-expanded="false" data-toggle="collapse"><i class="la la-send"></i><span>Transaksi Pengiriman</span></a>
					<ul id="dropdown-delivery" class="collapse list-unstyled pt-0">
						@role('Admin|Pimpinan')
						<li><a id="delivery-index-link" href="{{ route('delivery') }}">Data Pengiriman Selesai</a></li>
						<li><a id="delivery-active-link" href="{{ route('activeDelivery') }}">Data Pengiriman Aktif</a></li>
						<li><a id="delivery-cancel-link" href="{{ url('delivery/deliveryCancel') }}">Data Pengiriman Dibatalkan</a></li>
						<li><a id="add-delivery-link" href="{{ route('createDelivery') }}">Input Pengiriman</a></li>
						@endrole
						@role('Kurir')
						<li><a id="delivery-active-link" href="{{ url('delivery/activeDeliveryCourier') }}">Data Pengiriman Aktif</a></li>
						@endrole
					</ul>
				</li>
				@role('Admin|Pimpinan')
				<li id="courier-link"><a href="{{ route('courier.index') }}"><i class="la la-user-secret"></i><span>Data Kurir</span></a></li>
				<li id="expenses-link"><a href="{{ route('otherExpenses') }}"><i class="la la-sign-out"></i><span>Data Pengeluaran</span></a></li>
				<li id="setting-link"><a href="{{ route('setting.index') }}"><i class="la la-gear"></i><span>Setting</span></a></li>
				@endrole
			</ul>
			
			<!-- End Main Navigation -->
		</nav>
		<!-- End Side Navbar -->
	</div>
	<!-- End Left Sidebar -->
	<div class="content-inner">